Chernikov_Lessons/Lesson1/Lesson1/Models/Warrior.cs
using System;
using Ninject;
using Ninject.Modules;

namespace Lesson1.Models
{
    public class WeaponNinjectModule : NinjectModule
    {
        public override void Load() {
            Bind<IWeapon>().To<Sword>();
        }
    }

    public interface IWeapon
    {
        string Kill();
    }

    internal class Bazooka : IWeapon
    {
        public string Kill() {
            Console.WriteLine("Badaboom!!!");
            return "Badaboom!!!";
        }
    }

    internal class Sword : IWeapon
    {
        public string Kill() {
            Console.WriteLine("Chuck-chuck");
            return "Chuck-chuck";
        }
    }

    public class Warrior
    {
        [Inject]
        public IWeapon Weapon { get; set; }

        public string Kill() {
            return Weapon.Kill();
        }
    }
}

Chernikov_Lessons/Lesson1/Lesson1/Areas/Default/Controllers/DefaultController.cs
using Lesson1.Controllers;

namespace Lesson1.Areas.Default.Controllers
{
    public class DefaultController : BaseController
    {}
}

Chernikov_Lessons/Lesson1/Lesson1/Areas/Default/Controllers/HomeController.cs
using System.Web.Mvc;
using Lesson1.Controllers;
using Lesson1.Models;
using Ninject;

namespace Lesson1.Areas.Default.Controllers
{
    public class HomeController : BaseController
    {
        //private static readonly IKernel AppKernel = new StandardKernel(new WeaponNinjectModule());

        [Inject]
        public IWeapon Weapon { get; set; }

        // GET: Home
        public ActionResult Index() {
            //var warrior = AppKernel.Get<Warrior>();
            //ViewBag.WarriorMessage = warrior.Kill();

            return View(Weapon);
        }
    }
}

Chernikov_Lessons/Lesson1/Lesson1/Areas/Default/Controllers/RoleController.cs
using System.Linq;
using System.Web.Mvc;
using Lesson1.Controllers;

namespace Lesson1.Areas.Default.Controllers
{
    public class RoleController : BaseController
    {
        // GET: Role
        public ActionResult Index() {
            var roles = Repository.Roles.ToList();
            return View(roles);
        }
    }
}

Chernikov_Lessons/Lesson1/Lesson1/Areas/Default/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using Lesson1.Controllers;

namespace Lesson1.Areas.Default.Controllers
{
    public class UserController : BaseController
    {
        // GET: User
        public ActionResult Index() {
            var users = Repository.Users.ToList();
            return View(users);
        }
    }
}

Chernikov_Lessons/Lesson1/Lesson1/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LessonProject.Model;
using Ninject;

namespace Lesson1.Controllers
{
    public abstract class BaseController : Controller
    {
        [Inject]
        public IRepository Repository { get; set; }
    }
}

Chernikov_Lessons/Lesson1/Lesson1/Areas/Default/Views/Home/Index.cshtml
@model Lesson1.Models.IWeapon
@{
    ViewBag.Title = "Lesson project";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<h3>
    @*Warrior message - @ViewBag.WarriorMessage;*@
    @Model.Kill()
</h3>

<p>
    <div class="menu">
        <a href="@Url.Action("Index", "Role")">Roles</a>
        @Html.ActionLink("Users", "Index", "User")
    </div>
</p>

Chernikov_Lessons/Lesson1/Lesson1/Areas/Default/Views/Role/Index.cshtml
@model System.Collections.Generic.List<LessonProject.Model.Role>

@{
    ViewBag.Title = "Roles";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @foreach (var role in Model) {
        <div class="item">
            <span class="id">
                @role.ID
            </span>
            <span class="name">
                @role.Name
            </span>
            <span class="Code">
                @role.Code
            </span>
        </div>
    }
</p>

Chernikov_Lessons/Lesson1/Lesson1/Areas/Default/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@

</head>
<body>

@*
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("MVC Poker", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
*@

<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
</div>


@*@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")*@
@RenderSection("scripts", required: false)
</body>
</html>

Chernikov_Lessons/Lesson1/Lesson1/Areas/Default/Views/User/Index.cshtml
@model System.Collections.Generic.List<LessonProject.Model.User>

@{
    ViewBag.Title = "Users";
    Layout = "../Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

<p>
    @foreach (var user in Model)
    {
        <div class="item">
            <span class="id">
                @user.ID
            </span>
            <span class="email">
                @user.Email
            </span>
            <span class="AddedDate">
                @user.AddedDate
            </span>
        </div>
    }
</p>